version: '3.8'

services:
  frontend:
    image: node:20
    container_name: todo-frontend-dev
    working_dir: /app
    volumes:
      - .:/app  # Monta el directorio actual en /app dentro del contenedor
    ports:
      - "5173:5173"  # Expone el puerto 5173 (puerto predeterminado de Vite)
    environment:
      - VITE_BACKEND_URL=http://localhost:3000  # URL del backend
    command: sh -c "npm install && npm run dev"  # Instala dependencias y ejecuta el servidor de desarrollo
