version: '3.8'

services:
  frontend:
    image: node:20
    container_name: todo-frontend-dev
    working_dir: /app
    volumes:
      - ./todo-frontend:/app  # Monta el directorio del frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api  # URL del backend a través de Nginx
    command: sh -c "npm install && npm run dev"

  backend:
    image: node:16
    container_name: todo-backend-dev
    working_dir: /app
    volumes:
      - ./todo-backend:/app  # Monta el directorio del backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo
      - REDIS_URL=redis://redis:6379
    command: sh -c "npm install && npm run dev"

  mongo:
    image: mongo:6.0
    container_name: todo-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: todo-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:1.20.1
    container_name: todo-nginx-dev
    ports:
      - "8080:80"  # Expone el puerto 8080 en el host
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro  # Monta la configuración de Nginx
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  redis-data:
