version: '3.8'

services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-prod
    environment:
      - VITE_BACKEND_URL=http://localhost/api  # URL del backend a través de Nginx
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend-prod
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: todo-mongo-prod
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: todo-redis-prod
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:1.20.1
    container_name: todo-nginx-prod
    ports:
      - "80:80"  # Expone el puerto 80 en el host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Monta la configuración de Nginx
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  redis-data:
