services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"